services:
  db:
    image: postgres:16.10-alpine3.22
    container_name: mini-uber
    healthcheck:
      test: [ "CMD", "pg_isready", "-U"]
      interval: 5s
      retries: 10
    environment:
      POSTGRES_PASSWORD: postgresql
      POSTGRES_USER: postgresql
      POSTGRES_DB: uber-race
    ports:
      - "5432:5432"
    # ESSES COMANDOS S√ÉO USADOS PARA GARANTIR QUE O CDC FUNCIONE COM O WAL_LEVAL = LOGICAL
    command:
    - "postgres"
    - "-c"
    - "wal_level=logical"
    - "-c"
    - "max_replication_slots=5"
    - "-c"
    - "max_wal_senders=5"
    volumes:
      - ../data/uber-race:/var/lib/postgresql/data
